FROM docker.io/library/golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o worker ./cmd/worker

FROM gcr.io/distroless/static
COPY --from=builder /app/worker /app/worker
ENTRYPOINT ["/app/worker"]
